import cron from "node-cron";

import AutoGeneratedPlaylist from "#/models/autoGeneratedPlaylist";
import Audio from "#/models/audio";

/* The five fields in the cron syntax represent (in order) minutes, 
hours, day of the month, month, and day of the week*/

// Test : 2 seconds -> */2 * * * * *

const generatePlaylist = async () => {
  const result = await Audio.aggregate([
    { $sort: { likes: -1 } },
    {
      $sample: { size: 20 },
    },
    {
      $group: {
        _id: "$category",
        audios: { $push: "$$ROOT._id" },
      },
    },
  ]);

  result.map(async (item) => {
    await AutoGeneratedPlaylist.updateOne(
      { title: item._id },
      { $set: { items: item.audios } },
      { upsert: true }
    );
  });
};

cron.schedule("0 0 0 * * *", async () => {
  // Run every 24 hrs
  await generatePlaylist();
});
